apiVersion: v2
name: archive-node
description: A Helm Chart that deploys a Mina Archive Node, and the Rosetta API.
type: application
version: 0.5.2
appVersion: 1.16.0
annotations:
  artifacthub.io/changes: |
    - fix peer-list-url flag
dependencies:
  - name: postgresql
    version: "*"
    repository: "https://charts.bitnami.com/bitnami"
  - name: common-utilities
    version: 0.0.8
    repository: "https://mina-charts.storage.googleapis.com"
icon: https://storage.googleapis.com/mina-charts/Mina_Icon_Secondary_RGB_Black.png
keywords:
- archive
- postgres
- mina
- production
- sushi-validator
home: https://minastakingpool.connerswann.me/
sources:
- https://github.com/Sushi-Validator/helm-charts/tree/main/charts/archive-node
